name: Deploy to GitHub Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"
      
      - name: Setup Pages
        uses: actions/configure-pages@v4
      
      - name: Install dependencies
        run: |
          # Clean install for consistent builds
          npm ci --legacy-peer-deps || (rm -f package-lock.json && npm install --legacy-peer-deps)
      
      - name: Build with Next.js
        run: npm run build
      
      - name: Verify build output
        run: |
          echo "Build output contents:"
          ls -la out/
          echo "Static media directory (fonts):"
          ls -la out/_next/static/media/ || echo "No media directory found"
          echo "Custom fonts in public:"
          find out/ -name "*.woff2" -o -name "*.woff" || echo "No custom fonts found"
      
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./out

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4 